/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerBookingsRouteImport } from './routes/owner.bookings'
import { Route as OwnerProfileRouteImport } from './routes/owner.profile'
import { Route as OwnerUnitsRouteImport } from './routes/owner.units'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ReferralsIndexRouteImport } from './routes/referrals.index'
import { Route as ReferralsDashboardRouteImport } from './routes/referrals.dashboard'
import { Route as ReferralsGenerateRouteImport } from './routes/referrals.generate'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/owner/bookings',
  path: '/owner/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerProfileRoute = OwnerProfileRouteImport.update({
  id: '/owner/profile',
  path: '/owner/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerUnitsRoute = OwnerUnitsRouteImport.update({
  id: '/owner/units',
  path: '/owner/units',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsIndexRoute = ReferralsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReferralsRoute,
} as any)
const ReferralsDashboardRoute = ReferralsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ReferralsRoute,
} as any)
const ReferralsGenerateRoute = ReferralsGenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => ReferralsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/referrals/dashboard': typeof ReferralsDashboardRoute
  '/referrals/generate': typeof ReferralsGenerateRoute
  '/locations/': typeof LocationsIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/referrals/dashboard': typeof ReferralsDashboardRoute
  '/referrals/generate': typeof ReferralsGenerateRoute
  '/locations': typeof LocationsIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/referrals': typeof ReferralsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/saved': typeof SavedRoute
  '/terms': typeof TermsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/profile': typeof OwnerProfileRoute
  '/owner/units': typeof OwnerUnitsRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/referrals/dashboard': typeof ReferralsDashboardRoute
  '/referrals/generate': typeof ReferralsGenerateRoute
  '/locations/': typeof LocationsIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/referrals/': typeof ReferralsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/refund-policy'
    | '/saved'
    | '/terms'
    | '/locations/$slug'
    | '/owner/bookings'
    | '/owner/profile'
    | '/owner/units'
    | '/properties/$id'
    | '/referrals/dashboard'
    | '/referrals/generate'
    | '/locations/'
    | '/owner/'
    | '/properties/'
    | '/referrals/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/saved'
    | '/terms'
    | '/locations/$slug'
    | '/owner/bookings'
    | '/owner/profile'
    | '/owner/units'
    | '/properties/$id'
    | '/referrals/dashboard'
    | '/referrals/generate'
    | '/locations'
    | '/owner'
    | '/properties'
    | '/referrals'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/notifications'
    | '/privacy'
    | '/profile'
    | '/referrals'
    | '/refund-policy'
    | '/saved'
    | '/terms'
    | '/locations/$slug'
    | '/owner/bookings'
    | '/owner/profile'
    | '/owner/units'
    | '/properties/$id'
    | '/referrals/dashboard'
    | '/referrals/generate'
    | '/locations/'
    | '/owner/'
    | '/properties/'
    | '/referrals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRouteWithChildren
  RefundPolicyRoute: typeof RefundPolicyRoute
  SavedRoute: typeof SavedRoute
  TermsRoute: typeof TermsRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerProfileRoute: typeof OwnerProfileRoute
  OwnerUnitsRoute: typeof OwnerUnitsRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/owner/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/profile': {
      id: '/owner/profile'
      path: '/owner/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof OwnerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/units': {
      id: '/owner/units'
      path: '/owner/units'
      fullPath: '/owner/units'
      preLoaderRoute: typeof OwnerUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals/': {
      id: '/referrals/'
      path: '/'
      fullPath: '/referrals/'
      preLoaderRoute: typeof ReferralsIndexRouteImport
      parentRoute: typeof ReferralsRoute
    }
    '/referrals/dashboard': {
      id: '/referrals/dashboard'
      path: '/dashboard'
      fullPath: '/referrals/dashboard'
      preLoaderRoute: typeof ReferralsDashboardRouteImport
      parentRoute: typeof ReferralsRoute
    }
    '/referrals/generate': {
      id: '/referrals/generate'
      path: '/generate'
      fullPath: '/referrals/generate'
      preLoaderRoute: typeof ReferralsGenerateRouteImport
      parentRoute: typeof ReferralsRoute
    }
  }
}

interface ReferralsRouteChildren {
  ReferralsDashboardRoute: typeof ReferralsDashboardRoute
  ReferralsGenerateRoute: typeof ReferralsGenerateRoute
  ReferralsIndexRoute: typeof ReferralsIndexRoute
}

const ReferralsRouteChildren: ReferralsRouteChildren = {
  ReferralsDashboardRoute: ReferralsDashboardRoute,
  ReferralsGenerateRoute: ReferralsGenerateRoute,
  ReferralsIndexRoute: ReferralsIndexRoute,
}

const ReferralsRouteWithChildren = ReferralsRoute._addFileChildren(
  ReferralsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRouteWithChildren,
  RefundPolicyRoute: RefundPolicyRoute,
  SavedRoute: SavedRoute,
  TermsRoute: TermsRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerProfileRoute: OwnerProfileRoute,
  OwnerUnitsRoute: OwnerUnitsRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
